### ISSUE TITLE
Connecting to wrong port

### ISSUE THREAD

**Issue by InUrSys** [PyReportJasper/pyreportjasper#38]
Hi/Ola, first thank you for the amazing lib.
so basically my problem is when I try to generate a report using the command below:
`"C:\Users\IN_x32\Desktop\PescArt2.0 ToBuildSetUP\pyjasper\jasperstarter\bin\jasperstarter.exe" --locale pt_BR process "C:\Users\IN_x32\Desktop\PescArt2.0 ToBuildSetUP\ReportTemplates\Saidas_Provinica.jrxml" -o "C:\Data\FishTools\PescArte\Reports" -f pdf -t generic -u pes_admin -p root -H localhost -n pescarte --db-port 5454 --db-driver org.postgresql.Driver --db-url jdbc:postgresql://localhost/pescarte`

I get the erro:
`GRAVE: Connection error: 
org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:265)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)
	at org.postgresql.Driver.makeConnection(Driver.java:450)
	at org.postgresql.Driver.connect(Driver.java:252)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at de.cenote.jasperstarter.Db.getConnection(Db.java:140)
	at de.cenote.jasperstarter.Report.fill(Report.java:252)
	at de.cenote.jasperstarter.App.processReport(App.java:217)
	at de.cenote.jasperstarter.App.main(App.java:102)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.postgresql.core.PGStream.<init>(PGStream.java:68)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:144)
	... 10 more

Unable to connect to database: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.`

I think jasperstarter is connecting to the wrong port im using port 5454 on my project but is trying to connect to default postgres port 5432.

**Comment by jadsonbr** [comment]
You can change the connection port with the  `PORT` parameter as shown below

```python
# -*- coding: utf-8 -*-
import os
from pyreportjasper import JasperPy

def advanced_example_using_database():
    input_file = os.path.dirname(os.path.abspath(__file__)) + \
                 '/examples/hello_world.jrxml'
    output = os.path.dirname(os.path.abspath(__file__)) + '/output/examples'
    con = {
        'driver': 'postgres',
        'username': 'DB_USERNAME',
        'password': 'DB_PASSWORD',
        'host': 'DB_HOST',
        'database': 'DB_DATABASE',
        'schema': 'DB_SCHEMA',
        'port': '5454' #Here you switch to the port to be used
    }
    jasper = JasperPy()
    jasper.process(
        input_file,
        output_file=output,
        format_list=["pdf"],
        db_connection=con,
        locale='en_US'  # LOCALE Ex.:(en_US, de_GE)
    )
```

**Comment by InUrSys** [comment]
when I used to use default port (5432) it worked fine, but when I changed to 5454 than it happen.


### the dict with the parameters:
dictcon = {'database': 'pescarte',
 'driver': 'generic',
 'host': 'localhost',
 'jdbc_driver': 'org.postgresql.Driver',
 'jdbc_url': 'jdbc:postgresql://localhost/pescarte',
 'password': 'root',
 'port': '5454',
 'schema': 'public',
 'username': 'pescarte_admin'}

### Calling the jasperpy
jasper = jasperpy.JasperPy()
jasper.process(input_file= self.input_file, 
                   output_file= self.output_file, 
                   format_list= ["pdf"], 
                   parameters= {},
                   db_connection= dictcon,
                   locale='pt_BR')

### the command generated by pyreportjasper:
"C:\Users\IN_x32\Desktop\PescArt2.0 ToBuildSetUP\pyjasper\jasperstarter\bin\jasperstarter.exe" --locale pt_BR process "C:\Users\IN_x32\Desktop\PescArt2.0 ToBuildSetUP\ReportTemplates\Saidas_Provinica.jrxml" -o "C:\Data\FishTools\PescArte\Reports" -f pdf -t generic -u pescarte_admin -p kltd6j3f9 -H localhost -n pescarte --db-port 5454 --db-driver org.postgresql.Driver --db-url jdbc:postgresql://localhost/pescarte

### the output I get:
ago 31, 2018 5:04:06 AM org.postgresql.Driver connect
GRAVE: Connection error: 
org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:265)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)
	at org.postgresql.Driver.makeConnection(Driver.java:450)
	at org.postgresql.Driver.connect(Driver.java:252)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at de.cenote.jasperstarter.Db.getConnection(Db.java:140)
	at de.cenote.jasperstarter.Report.fill(Report.java:252)
	at de.cenote.jasperstarter.App.processReport(App.java:217)
	at de.cenote.jasperstarter.App.main(App.java:102)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.postgresql.core.PGStream.<init>(PGStream.java:68)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:144)
	... 10 more

Unable to connect to database: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

**Comment by jadsonbr** [comment]
Try adding the following `jdbc` data as follows:

```python
# -*- coding: utf-8 -*-
import os
from pyreportjasper import JasperPy

def advanced_example_using_database():
    input_file = os.path.dirname(os.path.abspath(__file__)) + \
                 '/examples/hello_world.jrxml'
    output = os.path.dirname(os.path.abspath(__file__)) + '/output/examples'
    con = {
        'driver': 'postgres',
        'username': 'pescarte_admin',
        'password': 'root',
        'host': 'localhost',
        'database': 'pescarte',
        'schema': 'public',
        'port': '5454' #Here you switch to the port to be used
        'jdbc_driver': 'org.postgresql.Driver',
        'jdbc_url': 'jdbc:postgresql://localhost:5454/pescarte', #Here we add the connection port
        'jdbc_dir': '/opt/driver/postgresql/' #Location where the connection driver jar is located
    }
    jasper = JasperPy()
    jasper.process(
        input_file,
        output_file=output,
        format_list=["pdf"],
        db_connection=con,
        locale='en_US'  # LOCALE Ex.:(en_US, de_GE)
    )
```

**Comment by InUrSys** [comment]
Hi, sorry for the delay.
Again thank you for your time and help, that was the thing it was missing the port on JDBC_URL
` 'jdbc_url': 'jdbc:postgresql://localhost:5454/pescarte'`
