### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 1)

### ISSUE THREAD

**Issue by davidlehrian** [PyReportJasper/pyreportjasper#66]
I got the following error when attempting to install pyreportjasper.

```
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\lehrian\envs\cc\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\lehrian\\AppData\\Local\\Temp\\pip-install-_d6pjin2\\pyreportjasper\\setup.py'"'"'; __file__='"'"'C:\\Users\\lehrian\\AppData\\Local\\Temp\\pip-install-_d6pjin2\\pyreportjasper\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\lehrian\AppData\Local\Temp\pip-pip-egg-info-4nmol1bb'
         cwd: C:\Users\lehrian\AppData\Local\Temp\pip-install-_d6pjin2\pyreportjasper\
    Complete output (10 lines):
    openjdk version "15" 2020-09-15
    OpenJDK Runtime Environment (build 15+36-1562)
    OpenJDK 64-Bit Server VM (build 15+36-1562, mixed mode, sharing)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\lehrian\AppData\Local\Temp\pip-install-_d6pjin2\pyreportjasper\setup.py", line 44, in <module>
        if check_java_version_1_8() is None:
      File "C:\Users\lehrian\AppData\Local\Temp\pip-install-_d6pjin2\pyreportjasper\setup.py", line 32, in check_java_version_1_8
        major, minor, _ = version_number.split('.')
    ValueError: not enough values to unpack (expected 3, got 1)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

(CC) C:\Users\lehrian>javac -version
javac 15
```

The error is because I have Java OpenJDK 15 installed instead of the expected Oracle JDK 8.  Does pyreportjasper only support Oracle JDK?  It this simply the installation script or is there a dependence on Oracle proprietary additions to the Oracle JDK?

**Comment by jadsonbr** [comment]
@davidlehrian pyreportjasper uses jasperstarter which currently only supports java 1.8. We are working to update these facilities.

[jasperstarter](http://jasperstarter.cenote.de)

**Comment by davidlehrian** [comment]
Here is a version of JasperStarter that works with OpenJDK 15.  https://bitbucket.org/dlehrian/jasperstarter/src/fix_for_URLClassLoader/
